### ISSUE TITLE
replace fb images for ep 62 and 63

### ISSUE THREAD

**Issue by bridgetkromhout** [arresteddevops/ado-hugo#177]
Need correct-sized fb images for https://github.com/arresteddevops/ado-hugo/pull/176/files and https://github.com/arresteddevops/ado-hugo/blob/master/content/episode/speaking.md as well.

**Comment by bridgetkromhout** [comment]
I think the social sharing sizes changed at some point so I'm not sure if this matters now. @mattstratton ?

**Comment by mattstratton** [comment]
Meh. If someone ever complains we will fix it.
