### ISSUE TITLE
Update iTunes description field to be more personal

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#209]
Per DJL, it should have more personal words, like "we", as in "we help you achieve", etc.

**Comment by bridgetkromhout** [comment]
How about...

"On Arrested DevOps, we chat with interesting people and invite you to the party. Our podcast helps you achieve understanding, develop good practices, and operate your team and organization for maximum DevOps awesomeness."

**Comment by mattstratton** [comment]
One thing that sticks out to me is that our guests are "real world" people with real experiences. I want to reflect that somehow.

**Comment by mattstratton** [comment]
I love "invite you to the party"

**Comment by bridgetkromhout** [comment]
Again, I think "Arrested DevOps is the podcast that helps you achieve understanding, develop good practices, and operate your team and organization for maximum DevOps awesomeness." is what we arrived at - do we need something else here?
