### ISSUE TITLE
List of upcoming conferences/cfps?

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#21]
This has been requested a LOT

**Comment by mattstratton** [comment]
Depends on #81

**Comment by bridgetkromhout** [comment]
Commented over on 81 - I don't want to be in the business of maintaining such a list. I'm okay with specifically name-checking ones we're involved with, but other than that, I think this is being solved by Neal.

**Comment by mattstratton** [comment]
This can be closed once we remove then link in the nav :)
