### ISSUE TITLE
Create better show-level description

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#211]
This will be used in the About page, as well as possibly be used somewhat in iTunes.

Some things to consider (this is just data Matt wrote about the show to explain it to DJL for the eval):
- We strive to help people who are getting started with DevOps (as well as seasoned practitioners) to "level up" their understanding of good practices in the industry, mostly by learning from our panels of real-world folks who are doing this in their companies today.
- We strive to help people who are getting started with DevOps (as well as seasoned practitioners) to "level up" their understanding of good practices in the industry, mostly by learning from our panels of real-world folks who are doing this in their companies today.
- We strive to help people who are getting started with DevOps (as well as seasoned practitioners) to "level up" their understanding of good practices in the industry, mostly by learning from our panels of real-world folks who are doing this in their companies today.

**Comment by bridgetkromhout** [comment]
I'm fine with this except I think "strive" is a bit unneeded. We _do_ do this.

**Comment by mattstratton** [comment]
Remember the context of the bullets - that's how I explained the show to Daniel. He literally said don't say those things exactly, but suggested I already wrote most of it by accident :)

**Comment by bridgetkromhout** [comment]
I think this is resolved by `Arrested DevOps is the podcast that helps you achieve understanding, develop good practices, and operate your team and organization for maximum DevOps awesomeness.` - what do we think?

**Comment by mattstratton** [comment]
Yeah, I think it's fine.
