### ISSUE TITLE
Optimize iTunes show title for SEO

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#212]
Don't rename the show - but add something.

For example, `Arrested DevOps - Optimize for Software Release Efficiency`

(that tagline is a BAD one, but it should get the idea)

The tagline should NOT be "cutesy" (this is not "There's always devops in the banana stand", but something that tells what you get from listening to the show.

Suggestions welcome.

**Comment by bridgetkromhout** [comment]
Arrested DevOps - Conversations with Interesting People
Arrested DevOps - Join the Conversation
Arrested DevOps - People, Process, and Tools

something like that?

**Comment by mattstratton** [comment]
Something like that, but better keywords :) not keyword spamming. I really don't know what yet because we do have "DevOps" in there already and that's our most important keyword.

**Comment by bridgetkromhout** [comment]
Given how long this has been pending, I propose we either pick something or resolve it WONTFIX (which is fine by me). :)

**Comment by mattstratton** [comment]
I'd say WONTFIX
