### ISSUE TITLE
update workflow with Joe

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#219]
A few things need to be updated with the audio workflow:
- Episode title should be the full title (i.e., "CareerOps with Jill Jubinski and Peter Burkholder"
- URL needs to be the URL to the episode page, not the homepage
- Description needs to go in the "Summary (Description)" box not the "Subtitle" box
- Cover Art needs to be added (at the minimum this should be the show-level image, but the square image for the episode would be good.)

The deliverable for this issue is a markdown file of the workflow that will be hosted in this repo.

**Comment by mattstratton** [comment]
Make sure to include in the workflow that the episode is not uploaded to auphonic without a PR for the episode with episode number.

**Comment by mattstratton** [comment]
For the record, I am not expecting Joe to write this workflow document; the actual assignee is me. I just wanted Joe to see it :)

**Comment by bridgetkromhout** [comment]
What if anything remains for @joelaha or you to do here?

**Comment by mattstratton** [comment]
I think we have this under control,
