### ISSUE TITLE
revisit url's for episodes

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#232]
Couple items here:
1. It's super handy to refer to the episode by number, and it's a better mnemonic. We stopped doing this on the show ("you can find the show notes at arresteddevops.com/71" because episode numbers started to drift. I think we can handle around this corner case by virtue of a better workflow (not having episodes sit for months at a time). Worst case scenario is we record episode 81, and before it gets released, we have a time-critical thing ("OMG, we have to do an episode about how Docker suddenly stopped working on Linux"), which makes the super critical episode be number 82, and number 82 gets released a few days/a week before 81. I don't think this is the end of the world.
2. It's good to have really easy short URLs that have no dashes, for reference on the show. So for example, we could tell people to visit `arresteddevops.com/devopscareers`, but the real URL of the episode is `http://arresteddevops.com/devops-career-with-jeff-hackert`, with an alias of both the episode number and `devopscareers`. The filename of the episode is `devops-career-with-jeff-hackert.md`.

**Comment by bridgetkromhout** [comment]
I don't care what we call the "friendly" URLs, but I do think it's a little tricky to pick a number in advance if we have race conditions.

**Comment by mattstratton** [comment]
See #251 for more.

**Comment by bridgetkromhout** [comment]
Resolved in https://github.com/arresteddevops/ado-hugo/issues/251 ? I think we have a practice of `/reasonable-friendly-thing` as it is now.

**Comment by mattstratton** [comment]
Yeah, we can close this. It's been fine.
