### ISSUE TITLE
change guest images to jpeg

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#233]
Few steps needed here:
- [ ] Convert all existing guest images to JPEG (leaving the PNG files in place)
- [ ] Update the code to look for `.jpg` instead of `.png` when pulling up a guest
- [ ] Update the README to tell people to make a JPEG instead of a PNG

**Comment by bridgetkromhout** [comment]
"With the new theme, this will work going forward using whichever type of image you want."

Does that apply to guest images as well?

**Comment by mattstratton** [comment]
Yep. In the frontmatter for the guest you set the image name.
