### ISSUE TITLE
update blogpage to use proper shortcode and feeds

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#237]
update the [content/page/blogs.md](https://github.com/arresteddevops/ado-hugo/blob/master/content/page/blogs.md) page to use the new shortcode (some examples in there).

**Comment by bridgetkromhout** [comment]
Is this what we're wanting to do for each entry?

```
- {{< bloglink url="https://www.ansible.com/blog" title="Ansible Blog" rss="https://www.ansible.com/blog/rss.xml" >}}

```

**Comment by mattstratton** [comment]
I *think* that's what I meant by this.

**Comment by bridgetkromhout** [comment]
Alternate suggestion: remove this page since we don't often update the content?

**Comment by mattstratton** [comment]
Agreed. I’ll remove the page and remove it from nav. I’ll also make the url redirect to the homepage so it doesn’t 404.
