### ISSUE TITLE
add some more books to the list

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#267]
The DevOps Handbook
Infrastructure as Code: Managing Servers in the Cloud
The Goal: A Process of Ongoing Improvement
Site Relabilty Engineering
Switch

**Comment by bridgetkromhout** [comment]
This is for https://www.arresteddevops.com/books which is edited at https://github.com/arresteddevops/ado-hugo/blob/master/content/page/books.md - I am opting out of curating a book list myself, but flagging @jessitron in case she's interested. Let's resolve this one?

**Comment by bridgetkromhout** [comment]
Resolving as @jessitron has added some books. We can always revisit this.
