### ISSUE TITLE
add social sharing images for pages that don't have them

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#268]
- [ ] https://www.arresteddevops.com/blogs/
- [ ] https://www.arresteddevops.com/podcasts/
- [ ] https://www.arresteddevops.com/books/ (also needs a description field)
- [ ] https://www.arresteddevops.com/about/ (also needs a better description field)
- [ ] https://www.arresteddevops.com/contact/ (also needs a better description field)
- [ ] https://www.arresteddevops.com/faq/ (also needs better description)
- [ ] https://www.arresteddevops.com/thanks-pals/ (also needs better description)

**Comment by bridgetkromhout** [comment]
Is this still something we're interested in?

**Comment by mattstratton** [comment]
I don't care about this anymore :)
