### ISSUE TITLE
Edit Introduction on config.toml

### ISSUE THREAD

**Issue by osolari** [arresteddevops/ado-hugo#306]
I'm trying to edit the welcome page and add some description. I use the command you have suggested to run the server. hugo server -w --baseUrl="http://localhost:1313". I can see my changes everywhere else like on episodes etc but the grey box, the introduction, does not change no matter how often I refresh.

**Comment by mattstratton** [comment]
I'm not sure why this would occur - I will say that I don't recommend trying to use this theme for a podcast other than ADO; it wasn't written to be super portable. That's why I created the [castanet](https://github.com/mattstratton/castanet) theme; in fact, we will be moving Arrested DevOps to that theme in the near future. 

What version of hugo are you using?

**Comment by osolari** [comment]
it's Hugo Static Site Generator v0.18.1.

I have seen the other one but it doesn't look nearly as good as this one though.

**Comment by mattstratton** [comment]
If you use the grid layout, it's very similar. I based it upon this theme :)

The grid layout functionality is not 100% complete, but as I mentioned, once I finish the development of Castanet for use with ADO, it will look exactly (with some improvements, actually) like the ADO theme.

I believe with that version of Hugo that changes to config.toml don't show up with the watch command.

**Comment by osolari** [comment]
Thanks Mat! Looking forward to your new developments on the theme. Something that I really like about the ado theme for example is that the title for each episode is overlaid on the thumbnail and looks like a part of it where as in castanet it's below it separately and looks separate from the thumbnail and I don't know how it'll behave once the title is longer than one line. Is the grid going to look asymmetric?

**Comment by osolari** [comment]
Also I really like the white background in ado. Hopefully it's easy to change the color theme in castanet. thanks again!

**Comment by mattstratton** [comment]
Closing this issue. If you need more help, let me know! Castanet is almost at v1!
