### ISSUE TITLE
remove unneeded travis build steps?

### ISSUE THREAD

**Issue by bridgetkromhout** [arresteddevops/ado-hugo#387]
Much like for ADO.

**Comment by mattstratton** [comment]
Or devopsdays, even

**Comment by bridgetkromhout** [comment]
Ah, yes. Indeed.

**Comment by mattstratton** [comment]
TBH, I am not 100% sure why we even need the travis steps, since Netlify accomplishes much the same things (all travis is doing is making sure the site can build).

I'm all for just removing it and not replacing it.

**Comment by bridgetkromhout** [comment]
> I'm all for just removing it and not replacing it.

Fine by me!
