### ISSUE TITLE
Old episodes URLs broken

### ISSUE THREAD

**Issue by smlx** [arresteddevops/ado-hugo#396]
Older episodes seem to be broken - e.g. https://www.arresteddevops.com/what-is-devops/ has a direct download link to https://media.blubrry.com/arresteddevops/content.blubrry.com/arresteddevops/arrested-devops-podcast-episode01.mp3 which is returning 403 for me.

**Comment by bridgetkromhout** [comment]
Thanks for reporting this, @smlx! I know we changed the theme in the way that it links to old eps. We'll look into this. In the meantime that specific ep is definitely available on youtube from that page.

**Comment by bridgetkromhout** [comment]
Hi, @smlx - thanks again for the report. We identified and corrected the problem, which existed for episodes 1 through 9. Enjoy!
