### ISSUE TITLE
Create Photoshop automation for episode banners

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#41]

**Comment by mattstratton** [comment]
This should actually be created for the new model (with pictures of guests) as I ended up finishing all the legacy banners by hand.

**Comment by bridgetkromhout** [comment]
I think we sometimes pick guest pics and sometimes a whimsical relevant image. Do we still want to do this?

**Comment by mattstratton** [comment]
I don't really remember what this was for. I have a way that works for me, and if it's working for everyone else, then yay!
