### ISSUE TITLE
allow for versioned bios for guests

### ISSUE THREAD

**Issue by bridgetkromhout** [arresteddevops/ado-hugo#52]
Allow for guests to have a versioned bio (possibly just a versioned name in https://github.com/arresteddevops/ado-hugo/tree/master/data/guests - so if they get a new job, the bio for the old episode is right-for-the-time).

**Comment by mattstratton** [comment]
I think we are sorta already doing this by just naming the guest differently. If you don't think this is an acceptable solution, @bridgetkromhout, leave this open. otherwise, please close it.

**Comment by mattstratton** [comment]
I'm going to close this, since our workaround seems sufficient.
