### ISSUE TITLE
Hyperlink text instead of displaying URLs

### ISSUE THREAD

**Issue by theDanielJLewis** [arresteddevops/ado-hugo#60]
In the show notes, you have the URLs in plain text. But it would be better if the relevant text was hyperlinked. It's more scannable, takes less space, helps with SEO, and it's more user-friendly.

**Comment by mattstratton** [comment]
I am thinking that you probably saw this mostly on old show notes; we should definitely go back through the old ones and clean them up to be hyperlinked properly. It likely was an artifact of the WP to markdown migration.

**Comment by bridgetkromhout** [comment]
Thanks for the suggestion, @theDanielJLewis! We've definitely started doing better linking in the show notes, and I think going back and updating old ones is probably not going to happen - but hopefully they're more usable going forward!
