### ISSUE TITLE
Make data files for conferences

### ISSUE THREAD

**Issue by mattstratton** [arresteddevops/ado-hugo#81]
There should be a data directory and YAML configuration to make CFP page (and possibly show notes even if we want to get slick) be data driven by upcoming confs/CFP's

**Comment by bridgetkromhout** [comment]
I think we should just point to http://devopsconferences.org/ instead of trying to maintain this data.

**Comment by mattstratton** [comment]
Yeah, maybe add a "links" under the resources nav or something.

**Comment by mattstratton** [comment]
I mean a links page. That links to things like devopsconferences, devopsdays, other websites that are useful but not books/podcasts/blogs

**Comment by bridgetkromhout** [comment]
Do we want to add new info to the "resources" nav? Maybe @jessitron has suggestions?

**Comment by mattstratton** [comment]
I'm definitely against curating a list of events since it's way too much work. Closing.
